# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yJ-rbe5HKgrEIjPhvPIo_zos-3dOdFlD
"""

from google.colab import files
uploaded = files.upload()

# Step 1: Import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, StandardScaler

# Step 2: Load dataset
df = pd.read_csv("Titanic-Dataset.csv")  # Make sure this matches your file name
df.head()

# Step 3: Explore data
print(df.info())
print(df.describe())
print(df.isnull().sum())

# Step 4: Handle missing values
df['Age'].fillna(df['Age'].mean(), inplace=True)
df['Cabin'].fillna('Unknown', inplace=True)
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

# Step 5: Encode categorical variables
le = LabelEncoder()
df['Sex'] = le.fit_transform(df['Sex'])
df = pd.get_dummies(df, columns=['Embarked'])

# Step 6: Scale numerical features
scaler = StandardScaler()
df[['Age', 'Fare']] = scaler.fit_transform(df[['Age', 'Fare']])

# Step 7: Visualize and remove outliers (e.g., Fare)
sns.boxplot(df['Fare'])
Q1 = df['Fare'].quantile(0.25)
Q3 = df['Fare'].quantile(0.75)
IQR = Q3 - Q1
df = df[~((df['Fare'] < (Q1 - 1.5 * IQR)) | (df['Fare'] > (Q3 + 1.5 * IQR)))]

# Done! Export to CSV if needed
df.to_csv("cleaned_titanic.csv", index=False)